"""
Spark protocol (by default in Ethereum mainnet)

Mainnet Addresses https://docs.sparkprotocol.io/developers/deployed-contracts/mainnet-addresses
"""

from defyes.constants import Chain

from .autogenerated import ProtocolDataProvider


class ProtocolDataProvider(ProtocolDataProvider):
    default_addresses: dict[str, str] = {
        Chain.ETHEREUM: "0xFc21d6d146E6086B8359705C8b28512a983db0cb",
    }
