"""
Autogenerated module. Don't change it manualy. Instead, import its classes into __init__.py or even derive them adding
extra methds.

# Inside __init__.py

from .autogenerated import TradingVault

# Optionally
class TradingVault(TradingVault):
    ...
"""

from karpatkit.cache import const_call
from karpatkit.node import get_node
from web3 import Web3

from defyes.generator import load_abi


class TradingVault:
    default_addresses: dict[str, str]

    def __init__(self, blockchain: str, block: int, address: str | None = None) -> None:
        self.block = block
        self.blockchain = blockchain
        if address:
            self.address = Web3.to_checksum_address(address)
        else:
            try:
                self.address = self.default_addresses[blockchain]
            except AttributeError as e:
                raise ValueError("No default_addresses defined when trying to guess the address.") from e
            except KeyError as e:
                raise ValueError(
                    f"{blockchain!r} not defined in default_addresses when trying to guess the address."
                ) from e
        node = get_node(blockchain)
        self.contract = node.eth.contract(address=self.address, abi=load_abi(__file__, "trading_vault.json"))

    def allowance(self, owner: str, spender: str) -> int:
        return self.contract.functions.allowance(owner, spender).call(block_identifier=self.block)

    def allowed(self, arg0: str) -> bool:
        return self.contract.functions.allowed(arg0).call(block_identifier=self.block)

    def allowed_to_interact(self, arg0: str) -> bool:
        return self.contract.functions.allowedToInteract(arg0).call(block_identifier=self.block)

    def balance_of(self, account: str) -> int:
        return self.contract.functions.balanceOf(account).call(block_identifier=self.block)

    @property
    def current_balance(self) -> int:
        return self.contract.functions.currentBalance().call(block_identifier=self.block)

    @property
    def decimals(self) -> int:
        return const_call(self.contract.functions.decimals())

    @property
    def get_price_per_full_share(self) -> int:
        return self.contract.functions.getPricePerFullShare().call(block_identifier=self.block)

    @property
    def name(self) -> str:
        return const_call(self.contract.functions.name())

    @property
    def owner(self) -> str:
        return self.contract.functions.owner().call(block_identifier=self.block)

    @property
    def pair_info(self) -> str:
        return self.contract.functions.pairInfo().call(block_identifier=self.block)

    @property
    def pending_owner(self) -> str:
        return self.contract.functions.pendingOwner().call(block_identifier=self.block)

    @property
    def standard_token(self) -> str:
        return const_call(self.contract.functions.standardToken())

    def standard_token_to_claim(self, arg0: str) -> int:
        return self.contract.functions.standardTokenToClaim(arg0).call(block_identifier=self.block)

    @property
    def symbol(self) -> str:
        return const_call(self.contract.functions.symbol())

    @property
    def total_rewards_distributed(self) -> int:
        return self.contract.functions.totalRewardsDistributed().call(block_identifier=self.block)

    @property
    def total_supply(self) -> int:
        return self.contract.functions.totalSupply().call(block_identifier=self.block)

    def user_last_deposit_time(self, arg0: str) -> int:
        return self.contract.functions.userLastDepositTime(arg0).call(block_identifier=self.block)

    @property
    def withdraw_timelock(self) -> int:
        return self.contract.functions.withdrawTimelock().call(block_identifier=self.block)
